# Generated by Django 5.1.7 on 2025-04-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bioimpedancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('vencido', 'VENCIDO')], default='ativo', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.aluno')),
            ],
        ),
    ]
