# Generated by Django 5.1.7 on 2025-04-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='core.aluno'),
        ),
    ]
