# Generated by Django 5.1.7 on 2025-05-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='status',
        ),
    ]
