# Generated by Django 5.1.7 on 2025-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_plano_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='status',
            field=models.CharField(choices=[('ativo', 'ATIVO'), ('vencido', 'VENCIDO')], default='ativo', max_length=10),
        ),
    ]
