# Generated by Django 5.1.7 on 2025-05-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plano_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.aluno'),
        ),
    ]
