# Generated by Django 5.1.7 on 2025-05-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_plano_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='core.aluno'),
        ),
    ]
