# Generated by Django 5.1.7 on 2025-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_plano_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioimpedancia',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
